Third-party cluster types are pluggable extensions to Cluster and Node
Extracts out all DSE code to such a plugin, under dse/
Adds HCD plugin, under hcd/
Adds smoke tests, creating/starting/stopping different ccm types, to the github actions (and run gha on all events).
Clean up README.md, pulling out some stuff to INSTALL.md

 patch by Mick Semb Wever; reviewed by Madhavan Sridharan, Brandon Williams for CASSANDRA-20456

Co-authored-by: Madhavan <msmygit@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,15 +18,12 @@ name: CI
 
 on:
   push:
-    branches: [ master]
   pull_request:
-    branches: [ master]
-
   workflow_dispatch:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
 
     steps:
       - uses: actions/checkout@v4
@@ -50,8 +47,25 @@ jobs:
         run: |
           pytest --junitxml=junit.xml tests
 
+      - name: Smoke tests
+        run: |
+          sudo ./setup.py install
+          set -x
+          ccm_test() { for i in {1..9}; do ./ccm start && ./ccm remove && return 0 || echo retrying; sleep 20; done; echo "ccm start failed after 9 attempts"; exit 1; }
+          export -f ccm_test
+          ./ccm create -h
+          ./ccm create test -v 5.0.3 -n1 --vnodes
+          ccm_test
+          ./ccm create test --version='git:cassandra-5.0.3' -n1 --vnodes
+          ccm_test
+          ./ccm create test -v 6.8.54 -n1 --vnodes --dse
+          ccm_test
+          # todo, when available
+          #./ccm create test -v 1.1.0 -n1 --vnodes --hcd
+          #ccm_test
+
       - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
+        uses: mikepenz/action-junit-report@v5
         if: always()
         with:
           report_paths: 'junit.xml'
